name: SEWoodyWetlands
channels:
  - defaults
dependencies:
  - alabaster=0.7.11=py27_0
  - appdirs=1.4.3=py27h28b3542_0
  - asn1crypto=0.24.0=py27_0
  - astroid=1.6.5=py27_0
  - attrs=18.1.0=py27_0
  - automat=0.7.0=py27_0
  - babel=2.6.0=py27_0
  - backports=1.0=py27_1
  - backports.functools_lru_cache=1.5=py27_1
  - backports.shutil_get_terminal_size=1.0.0=py27_2
  - backports.shutil_which=3.5.1=py27_2
  - backports_abc=0.5=py27h0ec6b72_0
  - blas=1.0=mkl
  - bleach=2.1.3=py27_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.13=py27_0
  - cffi=1.11.5=py27hdb016f4_0
  - chardet=3.0.4=py27_1
  - cloudpickle=0.5.3=py27_0
  - colorama=0.3.9=py27hdfe4ae1_0
  - configparser=3.5.0=py27h2fa79a8_0
  - constantly=15.1.0=py27h28b3542_0
  - cryptography=2.3=py27hc64555f_0
  - cryptography-vectors=2.3=py27_0
  - cycler=0.10.0=py27h59acbbf_0
  - decorator=4.3.0=py27_0
  - docutils=0.14=py27h8652d09_0
  - entrypoints=0.2.3=py27_2
  - enum34=1.1.6=py27_1
  - freetype=2.9.1=h4d385ea_1
  - functools32=3.2.3.2=py27_1
  - futures=3.2.0=py27_0
  - html5lib=1.0.1=py27_0
  - hyperlink=18.0.0=py27_0
  - icc_rt=2017.0.4=h97af966_0
  - icu=58.2=h2aa20d9_1
  - idna=2.7=py27_0
  - imagesize=1.0.0=py27_0
  - incremental=17.5.0=py27_0
  - intel-openmp=2018.0.3=0
  - ipaddress=1.0.22=py27_0
  - ipykernel=4.8.2=py27_0
  - ipython=5.8.0=py27_0
  - ipython_genutils=0.2.0=py27hbe997df_0
  - ipywidgets=7.4.0=py27_0
  - isort=4.3.4=py27_0
  - jedi=0.12.1=py27_0
  - jinja2=2.10=py27_0
  - jpeg=9b=ha175dff_2
  - jsonschema=2.6.0=py27haaf3834_0
  - jupyter=1.0.0=py27_5
  - jupyter_client=5.2.3=py27_0
  - jupyter_console=5.2.0=py27_1
  - jupyter_core=4.4.0=py27_0
  - keyring=13.2.1=py27_0
  - kiwisolver=1.0.1=py27hc56fc5f_0
  - lazy-object-proxy=1.3.1=py27h0c8e037_2
  - libpng=1.6.34=h325896a_0
  - libsodium=1.0.16=h8b3e59e_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.0=py27h0c8e037_1
  - matplotlib=2.2.2=py27habb2d18_2
  - mccabe=0.6.1=py27_1
  - mistune=0.8.3=py27h0c8e037_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.4=py27h31cbb53_1
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.3.1=py27_0
  - nbformat=4.4.0=py27hf49b375_0
  - notebook=5.6.0=py27_0
  - numpy=1.15.0=py27h911edcf_0
  - numpy-base=1.15.0=py27hfef472a_0
  - numpydoc=0.8.0=py27_0
  - openssl=1.0.2p=h0c8e037_0
  - packaging=17.1=py27_0
  - pandas=0.23.4=py27h39f3610_0
  - pandoc=2.2.1=h1a437c5_0
  - pandocfilters=1.4.2=py27_1
  - parso=0.3.1=py27_0
  - pathlib2=2.3.2=py27_0
  - pickleshare=0.7.4=py27hb5f6335_0
  - pip=10.0.1=py27_0
  - prometheus_client=0.3.1=py27_0
  - prompt_toolkit=1.0.15=py27h3a8ec6a_0
  - psutil=5.4.6=py27h0c8e037_0
  - pyasn1=0.4.4=py27_0
  - pyasn1-modules=0.2.2=py27_0
  - pycodestyle=2.4.0=py27_0
  - pycparser=2.18=py27_1
  - pyflakes=2.0.0=py27_0
  - pygments=2.2.0=py27ha50f84f_0
  - pylint=1.9.2=py27_0
  - pyopenssl=18.0.0=py27_0
  - pyparsing=2.2.0=py27_1
  - pyqt=5.6.0=py27h6e61f57_6
  - pysocks=1.6.8=py27_0
  - python=2.7.15=he216670_0
  - python-dateutil=2.7.3=py27_0
  - pytz=2018.5=py27_0
  - pywin32=223=py27h0c8e037_1
  - pywinpty=0.5.4=py27_0
  - pyzmq=17.1.0=py27h0c8e037_0
  - qt=5.6.2=vc9hc26998b_12
  - qtawesome=0.4.4=py27h766b13d_0
  - qtconsole=4.3.1=py27h77d40ac_0
  - qtpy=1.4.2=py27_1
  - requests=2.19.1=py27_0
  - rope=0.11.0=py27_0
  - scandir=1.9.0=py27h0c8e037_0
  - send2trash=1.5.0=py27_0
  - service_identity=17.0.0=py27h28b3542_0
  - setuptools=40.0.0=py27_0
  - simplegeneric=0.8.1=py27_2
  - singledispatch=3.4.0.3=py27h3f9d112_0
  - sip=4.18.1=py27hc56fc5f_2
  - six=1.11.0=py27_1
  - snowballstemmer=1.2.1=py27h28d3bf7_0
  - sphinx=1.7.6=py27_0
  - sphinxcontrib=1.0=py27_1
  - sphinxcontrib-websupport=1.1.0=py27_1
  - spyder=3.3.0=py27_0
  - spyder-kernels=0.2.4=py27_0
  - sqlite=3.24.0=h7a46e7a_0
  - terminado=0.8.1=py27_1
  - testpath=0.3.1=py27h1cd488d_0
  - tornado=5.1=py27h0c8e037_0
  - traitlets=4.3.2=py27h1b1b3a5_0
  - twisted=17.5.0=py27_0
  - typing=3.6.4=py27_0
  - urllib3=1.23=py27_0
  - vc=9=h7299396_1
  - vs2008_runtime=9.00.30729.1=hfaea7d5_1
  - wcwidth=0.1.7=py27hb1a0d82_0
  - webencodings=0.5.1=py27_1
  - wheel=0.31.1=py27_0
  - widgetsnbextension=3.4.0=py27_0
  - win_inet_pton=1.0.1=py27_1
  - win_unicode_console=0.5=py27hc037021_0
  - wincertstore=0.2=py27hf04cefb_0
  - winpty=0.4.3=4
  - wrapt=1.10.11=py27h0c8e037_2
  - zeromq=4.2.5=h2880e7c_1
  - zlib=1.2.11=hbc2faf4_2
  - zope=1.0=py27_0
  - zope.interface=4.5.0=py27h0c8e037_0
prefix: C:\Users\nmtarr\AppData\Local\Continuum\anaconda2\envs\SEWoodyWetlands

